CREATE TABLE IF NOT EXISTS User (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    student_id INT UNSIGNED NOT NULL UNIQUE,
    ex_1 BOOLEAN NOT NULL DEFAULT false,
    ex_2 BOOLEAN NOT NULL DEFAULT false,
    ex_3 BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (id)
    )
    ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS Ex1 (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    student_id INT UNSIGNED NOT NULL UNIQUE,
    PRIMARY KEY (id)
    )
    ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS Ex2 (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    student_id INT UNSIGNED NOT NULL UNIQUE,
    PRIMARY KEY (id)
    )
    ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS Ex3 (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    student_id INT UNSIGNED NOT NULL UNIQUE,
    PRIMARY KEY (id)
    )
    ENGINE=INNODB;